# Generated by Django 4.0.6 on 2022-07-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(help_text='Оригинальная ссылка')),
                ('cut_url', models.URLField(max_length=30)),
            ],
        ),
    ]
